#
# Appveyor CI configuration.
#

environment:
    matrix:
        - PYTHON: "C:/Python27"

install:
    - ps: (new-object net.webclient).DownloadFile("http://raw.github.com/pypa/pip/master/contrib/get-pip.py", "C:/get-pip.py")
    - "%PYTHON%/python.exe C:/get-pip.py"
    - "%PYTHON%/Scripts/pip.exe -q install cx_Freeze"

build_script:
    - "%PYTHON%/python.exe %PYTHON%/Scripts/cxfreeze secho.py --target-dir ."

test_script:
    - "secho.exe normal text OK"
    - ps: "cat appveyor.yml | ./secho.exe"

on_success:
    - ps: "rm secho.exe"
