#
# Appveyor CI configuration.
#
environment:
    matrix:
        - PYTHON: "C:/Python27"
init:
    - "ECHO %PYTHON%"

install:
    - ps: (new-object net.webclient).DownloadFile("http://raw.github.com/pypa/pip/master/contrib/get-pip.py", "C:/get-pip.py")
    - "%PYTHON%/python.exe C:/get-pip.py"
    - "%PYTHON%/Scripts/pip.exe -q install cx_Freeze"
    - ps: "ls %PYTHON%"

build_script:
    - "cxfreeze secho.py --target-dir dist"
