#
# Appveyor CI configuration.
#
environment:
    pip: "http://raw.github.com/pypa/pip/master/contrib/get-pip.py"
    matrix:
        - PYTHON: "C:/Python27"
init:
    - "ECHO %PYTHON%"
    - ps: "ls C:/Python27"

install:
    - ps: (new-objectt net.webclient).DownloadFile("%pip%", "C:/get-pip.py")
    - "%PYTHON%/python.exe C:/get-pip.py"
    - "%PYTHON%/Scripts/pip.exe -q install cx_Freeze"

test_script:
    - "cxfreeze secho.py --target-dir dist"
